[tool.ruff]
exclude = [
  ".venv-forecast",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
]

[tool.black]
exclude = '''
/(
    \.venv-forecast
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
)/
'''
